### ISSUE TITLE
Installation without conda possible?

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [claudiom4sir/StableVSR#7]
Hi,

I am not using conda usually, just the basic tools for python installation, like pip and venv. 
Would it be possible for you to describe how the installation would have to go then?
I tried but ran into problems concerning the cuda version and also the version of torch probably. 

Maybe even more user-friendly would be a .bat file containing all the code you need to run to install it with the only requirement that you have a python version installed before you run it.

Much too often installation of research software is just too difficult or time costly. Thanks! :)

**Comment by claudiom4sir** [comment]
Hi, the installation without Conda should be quite easy. Provided you have the correct Python version installed, you can simply install the required libraries via `pip install -r requirements.txt`. Dealing with CUDA versions may be hard, that's why I suggest you use Conda, to avoid interferences with any pre-installed NVIDIA driver and CUDA libraries.
